language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-26
  - secure: LG2ZgoDuxq1r0f6M88zwj2J6DCvzFFrvYAZgLklR/xXTNA3UULVNSf6Lt2yUxsXwqcHI4pW/P2+avH/S2ugal3jIWi/8B29P2fa5otBZP05UO6Hz2O3/rl2NdRqvETAYXGjbeVg9CDvShdpCsiJeGBvpgPd9clU3/tvNNpueVIAC0R/uZI9wsBkQKsaPiy0oL+SrFUqPlkbui2y0/PufaJuo8r3/LrX8NTdhem5622JbD95PV6xlLkmOKQKIsMi93F7Gh7np4fsXo9vyjs+Tc3GK0jqq8IPFChNPoaAFVntT2PKeGQNmcj9ISNQA/gmPBdr3BTwR0KLLF3HaF7dQ7RhqIJdmu8VoFXhpHyQ8N1iLYqtfb0vyFUAAHufyX4Ur3Xsp/oj3EXiJjznOUpxnS9ZbEPPa7o9mLKsEOfrvlFqyvgmDn7DCPyTw3DxxnkHMbyBS+/cOD4thZ17raJsgwCb8u2mn8uGg0TY+qaJaIMC97+0HiQ90pbNgGHBsmWAQP2mrU+1Paet0E70SepaT6rBXfRAf7blLwOgYiP+gKTuZmc1KWoXPtpqMkXc8uhSyzDo2dG4YyWNPl+bsWBldtQMXXYqWyZEpX3OJo+CRXkf+LcvWelnJthhiZZt6ldqInh8uh428klE0DExgLO5YyxENAUgs5b3RlceCMO1DMWk=
  - secure: ecjEID3izCKKbhAj9bVQsH/q7pk4vKoczTJxdwWB9U9xG0jkjay63ilOmoCDxAMRZv3b009beDB4whMHFKH1mWMNqWq4RDjUGkodUF0nT+jLyfsJC62C7qey46saSSYAa+mHXc+DRkQeFrWthXr5G8i+siV4RdfNM7R/HgtPNKpYbVDhYhX1crKM6WS0eAiiwEi1lP1TieDWdqgYXOPKage9QQ0TGxBbdJ+GBjH1QzzHYg83WhOQ5u44Brka9jSMGzvSlYntNAApKPqH0P+WZLXeI5/ROIjpJAYIvQIGoiZhwmLHEbT2IlXg1ZL86tEJeQ0O0UQcNnnzBvcEdQDc10r2PDgujD20y72GO9t6hxC4S4a/7RxaYgd9ZOirdWXquSsa6zh9SpDaJg6aad3UKyTUi0xtqMiKdTwfIb+So9GIwT4yccvnpheGJKnABa65qshn+dU0LZ69FYucJm7DwwgU9tgT+C+uI347UvAAENJ7L1pAL0NRvkRCds1+lBHFtTzhk4fSX2sJKo0g/drxokm30Ik50fHv6ki+RmrLqtM3P7oiGwWe6Csk1DYQOUpS4VqpCVmHI+pSa4IKNL0I4XJQ2vhLgko4DFq1n/SyX44icR2fyzHIFTtIMUZJZkqMB5rK0WvOMLeIxsm85atKTmUUeINana5dwyAKCesJIng=
  - secure: ShfgJJrHQRhp2tPu65FtiJedINO9JyjWo4/8uOcf2s0FJwc7j5RT+2mBrYrNvE+Y3QTZCvN6ZawE/6NhDzXXcRpqoz/f4ixNwl5QOzHgcUKFPIwuNH9b5FTMVU3YThgG8z7jJxmeOjxldwgdvKbqaOR/o1qLHiGEHSyqR4JC+Y2lzU0e61lN5Zjb7I9OtqiAyuct/hP5YoTYgnEJf+tkAhBTiHd6vX0K17pCWHwLZhevol9rxcII+dz4UwkyAnJDWPENeQirPwC7AsKbtcoUd2CVgEAu626hKrvFafIC+sWdwJCHGfjnC1vF5It5gX9bwNSv0VF1BwJRsJ5LNMMDD8kmsHNRgqB4Jnz0gKDDaWDN/GN5MxzvKE5FQYSr4x5G7ELigshW5+Bk3wy+FQK/ha7lvkqepJGk/PwMeUmzcJAP02akariTRsLWRq/5SQbF9sZ/I0PlCTA2aCXoqULMZ0UT/sqrGpyGk+53xbEizYx0shymV7KGVmQvnkoQLMW2HPV8TNI4tkh2TR9kWk1DlAkfm4I07K6Y7TUMskeALpvrr7Ckoc7h4agfbhOde5e9Ox/9TQ+7Sagitlir1pVDa30ky0ibTVvb69DnysZP740r3SFTFAK9SzVHi9htybd9AbR8Uwdzdc6neXaNgLg/Ng9QDq78xGn02na56t38xKw=
  - secure: bAaM0naq9/vDCLCg2UKKq5HyoU62/+ETHLts6At4xob7y/PUXj9VGW2WK9XPTHQQ4GaP9C9FxdjOeiOXGwOEUqjVupFlIOTM2rCmGgO8dnJFJ/NuS07IciygKcjJr4pahRmbrdyhFWgNoIFhYkshico4WD7gJPGNogHZ7o4oIMwTWDmhxL87QWUwmaZf1iWsmph8akdKlZjfDlZHAmI/GA+lmy4n192KLhvfaX2VHWfFxHqKGP4Y1j2Oyb3BkTKWqknNoaJJZ6e75AbxSp4Uay2DPhLST+xEb7l394lVTKViH3dfEHKRVNSuLzGsKqICJEoMwmwQcm+BtfU2+e5XtJMjI/bjJ2FDDhZIeeIyLU8w0tCdOVJjQEw334eMrYRTPA+Y6N9dwF1QVHQGglk9zg2a+0xapVku5JuSGrhfkLB9iRvlfi5o7s9eHNfJQYYaQ76P6m8zBh3v6QSYlQh1MJGq3X8FfCKhalpj6ScIiK5Y4GISUgs1Bwm3sicePRix6DQhzxh2jlU5UYYAArOG470/CDRqtjj0uKjtYuJEexApnbYzuVhm/DHT7mGbH/lK5z3GS30qXRC4UKO8FuZljYBT9uliX9/GUQ7SFw+gQwZ38BK+e/84kAG0/yt7iFB9pGwnn2dOFDakkNrKyxCpIswH7H6aXdt6h3pEelPZnyc=
  - secure: RGWBgi4H9M9ewrHjktBUVmaEYsSXVBuM/15Lxk7ZufmuFaD9Ah1LnkTIyUFcJdcW8MFah2onTZuNkhUlHmeH1GGwEKDqJbMZPlWtxJk7nEWl01gYBHfRhfOfKSAcCY0wO12V85/H+pArxzFeMu61Ooxas8URGxILOp4TQMBQ0ksKiBKLcNxlD/lnpgwlOq9ftYlu54BV8Kqpj72pih2/DDAMcIgEI4ZGJjr6ldD5rRyb42f/dEe8Rf2oC5lmlWgMOHHOY37Er2vLqKlTPmKOKHLYpAWfP6+hjlBD3hN8JyEkjuYbZ5X9h+eH6sJw4HygTLopcqpGhvB0eBwy5JmIKVOLf38x9EjpuldRHHNr0FMk11or5roG5XfHL97gLBHEYfp7YJPkpylgJFA3nfI7t2c6dAu8fLcLWP8rTwlP4wHWA1Jzy4vzBwNR4+Oi541Zb87FCVKhn1xRqP/n55xMjdijeg+Sk016uOSSLeOPbnf1HP/u1dfGWvZ8SEXrquRwwssG2K18nNaADRJIwG0LiZ16YHVTL8yETatcAPB25bgnV7PGD16fJ+kps5p4Hq5LrLxPvSoANUZf3c+jWJGhsds+Vix7ncyiwn29CN5JTkInTAzbB5Q/jtfuKJedmzSu8uUK/LglK+zTNd34q8KUca6gN7reRAa+QKZqW5SSI6Q=
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - addon-google_apis-google-19
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script: "./gradlew clean assembleRelease bintrayUpload"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
