language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-26
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - addon-google_apis-google-19
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script: "./gradlew clean build assembleRelease bintrayUpload"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
- openssl aes-256-cbc -K $encrypted_b2a9622817ea_key -iv $encrypted_b2a9622817ea_iv
  -in my.properties.enc -out my.properties -d
deploy:
  provider: releases
  api_key:
    secure: TPF19h6DTIctjVPYnlEWEjT7CYXMEVc3hxl1TN+c47j29BMy9o5E6kUylXvr9OyUvv8JTM2O2gjCf6wYHvlDAZjjVKKQ27DxBVinQZTqeb7FOAvTFdjSJcBvdLPms+9uUPJkqFKGP5ILNNE/pShMv5d/B1I3eH/RgR2qxzIlp9ySTawyqTzDy29qqN0U9WqhlXxl6psJoOIzxVHFdakmc/u03JSTaHz66Kae8S5qkYjA8XPYskYgVDJ7YDGrKPWmc2fEytKinp4AEXi+kSK1/v9tINaJGASJKpWVAGSM9HxOOvrOtwnTATzi5b6I/bnqhGOfjIbTgmTKnRm817xarZDNQcU2l515mbfw/zU08UweT0rS+TDehlqd0aVwc/gr8XawAslwg4oOVeK+Tm6HIeo57KLctfR0mHL+Y0nulFn+z4s1SYCvE7EvkNfWfmf5HfbvjY6oSh/yIrYrAOJ1Liiys2aO31AkaJZjoAM4DKNmqW0L4T/BE9/SMRVBhomuGfxV5Ude20RR8FxUJ3Ls4/dl21+n/1iZHc1KKcwmaICQB8C7fht4uxN22YurWFJSnxYbZcaHwBdcxxK76pjhoRIBWNvWMfCQrQin10/p7iVAVdPc26gNPnjxwZKosIaqYhf2l4J/tQ7ot6xhP94ChkrtPwLiAG7J+PvzeDbpgBk=
  file: keypad/android-view-keypad/app/build/outputs/apk/release/*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: HousebrandApps/android-view-keypad
    branch: release
after_success:
- sh set_tags.sh
