language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
script:
    /.gradlew clean assembleRelease